[package]
name = "vmi-utils"
version = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

homepage = { workspace = true }
repository = { workspace = true }
description = "Utilities for VMI"
keywords = [
    "vmi",
]

[lints]
workspace = true

[dependencies]
memmap2 = { workspace = true }
tracing = { workspace = true }
zerocopy = { workspace = true }

isr-cache = { workspace = true }
isr-core = { workspace = true }
isr-dl-windows = { workspace = true, optional = true } # CodeView
isr-macros = { workspace = true }

vmi-core = { workspace = true }
vmi-arch-amd64 = { workspace = true, optional = true }
vmi-arch-arm64 = { workspace = true, optional = true }
vmi-os-windows = { workspace = true, optional = true }

[dev-dependencies]
vmi = { workspace = true, features = ["arch-amd64", "os-windows", "utils"] }

[features]
default = []

arch-amd64 = ["vmi-arch-amd64"]
arch-arm64 = ["vmi-arch-arm64"]
os-windows = ["vmi-os-windows", "isr-cache/windows", "isr-dl-windows"]

bpm = ["interceptor", "ptm"]
bridge = []
injector = ["bridge"]
interceptor = []
ptm = []
# TODO: remove dependency on `arch-amd64` and `os-windows`
reactor = ["arch-amd64", "bpm", "os-windows", "resolver"]
reactor-arm64 = ["arch-arm64", "bpm", "os-windows"]
resolver = []
